// Bundles every .scad source the browser needs (vendored upstreams +
// lib + parts + assemblies) into one JSON blob, and copies
// catalogue.yaml alongside it, so the app can fetch its whole virtual
// filesystem in one request instead of one per file. Run before
// dev/build (see package.json), and re-run live by
// vite-plugin-scad-watch.mjs while `npm run dev` is up.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = path.resolve(__dirname, "..", "..");
export const WEB_PUBLIC = path.resolve(__dirname, "..", "public");

// Vendored upstreams are listed by the narrowest subtree the parts
// actually reach into. QuackWorks in particular is a large repo of
// unrelated systems; bundling all of it would put ~800KB of dead
// source in front of every visitor.
export const SOURCE_DIRS = [
  "vendor/BOSL2",
  "vendor/gridfinity-rebuilt/src",
  "vendor/GoProScad",
  "vendor/QuackWorks/openGrid",
  "lib",
  "parts",
  "assemblies",
];

// Upstreams written for OpenSCAD's library folder ask for their
// dependencies by library name — `include <BOSL2/std.scad>` — which
// resolves via OPENSCADPATH on a real install. There is no OPENSCADPATH
// in the WASM build, so those includes would simply not resolve.
// OpenSCAD does look next to the including file first, so a one-line
// redirect placed there is enough, and costs a few dozen bytes instead
// of a second copy of BOSL2.
const LIBRARY_INCLUDE = /^\s*(?:include|use)\s*<([^./][^>]*)>/gm;

// Directories inside an upstream that no part reaches into. BOSL2's
// examples alone are ~246KB of source the browser would download and
// never parse.
const SKIP_DIRS = new Set([".git", "examples", "tests", "tutorials", "scripts"]);

function walk(dir, out) {
  if (!fs.existsSync(dir)) return;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      walk(full, out);
    } else if (entry.name.endsWith(".scad")) {
      out.push(full);
    }
  }
}

function libraryRoots() {
  return new Set(
    fs
      .readdirSync(path.join(REPO_ROOT, "vendor"), { withFileTypes: true })
      .filter((e) => e.isDirectory())
      .map((e) => e.name),
  );
}

// For every `include <Lib/x.scad>` in a bundled file, emit a stub next
// to that file which forwards to the real vendor/Lib/x.scad.
function addLibraryShims(bundle) {
  const roots = libraryRoots();
  const shims = {};

  for (const [rel, content] of Object.entries(bundle)) {
    const dir = path.posix.dirname(rel);
    for (const match of content.matchAll(LIBRARY_INCLUDE)) {
      const target = match[1];
      const lib = target.split("/")[0];
      if (!roots.has(lib)) continue;

      const shimPath = path.posix.join(dir, target);
      if (bundle[shimPath] || shims[shimPath]) continue;

      const realPath = path.posix.join("vendor", target);
      if (!bundle[realPath]) continue;

      const hop = path.posix.relative(path.posix.dirname(shimPath), realPath);
      shims[shimPath] =
        `// Generated by sync-scad.mjs: forwards a library-path include to\n` +
        `// the vendored copy, since the WASM build has no OPENSCADPATH.\n` +
        `include <${hop}>\n`;
    }
  }
  return shims;
}

// Top-level `NAME = <simple literal>;` assignments in lib/constants.scad
// — the browser's copy of catalogue defaults for the "same override
// layer" global settings (FIT_CLEARANCE etc.), so the UI has a real
// catalogue-default number to diff/reset against instead of a
// hand-duplicated one. Only plain number/bool/quoted-string literals
// are picked up (the vast majority of constants.scad); a computed
// expression is skipped rather than guessed at, same spirit as
// cli/foundry.py's constants_names() only checking the name exists —
// this is that plus the value, best-effort.
const GLOBAL_CONST = /^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([^;]+);/gm;

function parseSimpleLiteral(raw) {
  const trimmed = raw.trim();
  if (trimmed === "true") return true;
  if (trimmed === "false") return false;
  if (/^-?\d+(\.\d+)?$/.test(trimmed)) return Number(trimmed);
  if (/^"[^"]*"$/.test(trimmed)) return JSON.parse(trimmed);
  return undefined; // computed expression — not a catalogue default we can show
}

function globalConstants() {
  const source = fs.readFileSync(path.join(REPO_ROOT, "lib", "constants.scad"), "utf8");
  const values = {};
  for (const match of source.matchAll(GLOBAL_CONST)) {
    const value = parseSimpleLiteral(match[2]);
    if (value !== undefined) values[match[1]] = value;
  }
  return values;
}

export function syncScad() {
  const bundle = {};
  for (const dir of SOURCE_DIRS) {
    const files = [];
    walk(path.join(REPO_ROOT, dir), files);
    for (const file of files) {
      const rel = path.relative(REPO_ROOT, file).split(path.sep).join("/");
      bundle[rel] = fs.readFileSync(file, "utf8");
    }
  }
  Object.assign(bundle, addLibraryShims(bundle));

  fs.mkdirSync(WEB_PUBLIC, { recursive: true });
  fs.writeFileSync(path.join(WEB_PUBLIC, "scad-bundle.json"), JSON.stringify(bundle));
  fs.copyFileSync(path.join(REPO_ROOT, "catalogue.yaml"), path.join(WEB_PUBLIC, "catalogue.yaml"));
  fs.writeFileSync(path.join(WEB_PUBLIC, "global-defaults.json"), JSON.stringify(globalConstants()));

  return Object.keys(bundle).length;
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);
if (isMain) {
  const count = syncScad();
  console.log(`sync-scad: bundled ${count} .scad files, copied catalogue.yaml`);
}
